external_components:
  source:
    type: git
    url: https://github.com/luigi-pi/fingerprint_fpc2532.git
    ref: main
  components: [fingerprint_FPC2532]

esphome:
  name: fingerprintfpc2532

esp32:
  variant: esp32
  framework:
    type: esp-idf

wifi:
  ssid: !secret my_ssid
  password: !secret my_pw
  fast_connect: true
  ap:
    ssid: "FPC Fallback"
    password: !secret AP_fallback_pw

captive_portal:

logger:

ota:
  platform: esphome
  password: !secret my_OTA_Pw

uart:
  rx_pin: GPIOXX
  tx_pin: GPIOXX
  baud_rate: 921600
  rx_buffer_size: 2048
  rx_timeout: 1

fingerprint_FPC2532:
  id: fpc2532
  # IMPORTANT: replace this with the unique_id seen in logs during first boot
  password: !secret unique_id_pw

  enroll_timeout_s: 5s

  on_finger_scan_matched:
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Fingerprint Authorized"
    - light.turn_on:
        id: green_led
    - delay: 1s
    - light.turn_off:
        id: green_led

  on_finger_scan_unmatched:
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Fingerprint NOT Authorized"
    - light.turn_on:
        id: red_led
        effect: Flash
    - delay: 1s
    - light.turn_off:
        id: red_led

  on_enrollment_scan:
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "On enrollment"
    - light.turn_on:
        id: green_led
    - light.turn_on:
        id: blue_led
        effect: Breathing
    - delay: 200ms
    - light.turn_off:
        id: green_led

  on_enrollment_failed:
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Enrollment failed"
    - light.turn_on:
        id: red_led
        effect: Flash
    - delay: 3s
    - light.turn_off:
        id: red_led
    - light.turn_off:
        id: blue_led
    - light.turn_off:
        id: green_led

  on_enrollment_done:
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Enrollment successful"
    - light.turn_on:
        id: green_led
    - delay: 3s
    - light.turn_off:
        id: green_led
    - light.turn_off:
        id: blue_led

  on_finger_scan_start:
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Verify fingerprint"
    - light.turn_on:
        id: blue_led
        effect: Flash
    - delay: 0.5s
    - if:
        condition:
          binary_sensor.is_on: enrolling_binary
        then:
          - light.turn_on:
              id: blue_led
              effect: Breathing
        else:
          - light.turn_off:
              id: blue_led

  on_finger_scan_invalid:
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Fingerprint verification error"
    - light.turn_on:
        id: red_led
        effect: Flash
    - delay: 3s
    - light.turn_off:
        id: red_led

api:
  encryption:
    key: !secret my_api_password
  custom_services: true

  services:
    - service: enroll
      variables:
        finger_id: int
      then:
        - fingerprint_FPC2532.enroll:
            finger_id: !lambda 'return finger_id;'

    - service: cancel_enroll
      then:
        - fingerprint_FPC2532.cancel_enroll:

    - service: delete
      variables:
        finger_id: int
      then:
        - fingerprint_FPC2532.delete:
            finger_id: !lambda 'return finger_id;'

switch:
  - platform: restart
    name: "Fingerprint Sensor Restart"

binary_sensor:
  - platform: fingerprint_FPC2532
    enrolling_binary:
      id: enrolling_binary
      name: "Enrollment Active"

  - platform: fingerprint_FPC2532
    uart_irq_before_tx:
      name: "UART IRQ Before TX"

  - platform: fingerprint_FPC2532
    status_at_boot:
      name: "Status At Boot"

  - platform: fingerprint_FPC2532
    stop_mode_uart:
      name: "Stop Mode UART"

text_sensor:
  - platform: fingerprint_FPC2532
    id: text_status
    name: "Sensor Status"

  - platform: fingerprint_FPC2532
    id: unique_id
    name: "Unique Hardware ID"

  - platform: fingerprint_FPC2532
    id: version
    name: "Version"

  - platform: template
    id: fingerprint_state
    name: "Scan Result"

  - platform: template
    id: text_enrollment_feedback
    name: "Enrollment Feedback"

sensor:
  - platform: fingerprint_FPC2532
    fingerprint_count:
      name: "Number of Fingerprints"
      accuracy_decimals: 0

    last_finger_id:
      name: "Last Matched Finger"
      accuracy_decimals: 0

    num_scans:
      name: "Enrollment Scans Remaining"

    status:
      name: "Status Code"
      id: status
      internal: true

    baud_rate:
      name: "UART Baud Rate"
      accuracy_decimals: 0

    scan_interval_ms:
      name: "Scan Interval (ms)"
      accuracy_decimals: 0

    uart_dly_before_tx_ms:
      name: "UART Delay Before TX (ms)"
      accuracy_decimals: 0

    idle_time_before_sleep_ms:
      name: "Idle Time Before Sleep (ms)"
      accuracy_decimals: 0

    lockout_after_nr_of_fails:
      name: "Lockout After Failures"
      accuracy_decimals: 0

    lockout_time_s:
      name: "Lockout Time (s)"
      accuracy_decimals: 0

    enroll_timeout_s:
      name: "Enrollment Timeout (s)"
      accuracy_decimals: 0

    enrollment_feedback:
    #This is added as yaml in order to add the possibility of easily translate it in different languages
      id: num_enrollment_feedback
      internal: true
      name: "Enrollment Feedback (textual)"
      on_value:
        then:
          - lambda: |-
              switch ((int)id(num_enrollment_feedback).state) {
                case 8: id(text_enrollment_feedback).publish_state("Touch the sensor to enroll"); break;
                case 1: id(text_enrollment_feedback).publish_state("Enrollment completed"); break;
                case 2: id(text_enrollment_feedback).publish_state("Record fingerprint"); break;
                case 3: id(text_enrollment_feedback).publish_state("Discarded: bad quality"); break;
                case 4: id(text_enrollment_feedback).publish_state("Discarded: low coverage"); break;
                case 5: id(text_enrollment_feedback).publish_state("Discarded: low mobility"); break;
                case 6: id(text_enrollment_feedback).publish_state("Discarded: unspecified"); break;
                case 7: id(text_enrollment_feedback).publish_state("Recorded: immobile"); break;
                default: id(text_enrollment_feedback).publish_state("Unknown status"); break;
              }

light:
  - platform: monochromatic
    id: red_led
    output: output_red
    default_transition_length: 25ms
    restore_mode: ALWAYS_OFF
    effects: &led_effects
      - pulse:
          name: Breathing
          transition_length: 0.5s
          update_interval: 0.5s
      - strobe:
          name: Flash
          colors:
            - state: true
              brightness: 100%
              duration: 125ms
            - state: false
              duration: 125ms

  - platform: monochromatic
    id: green_led
    output: output_green
    default_transition_length: 25ms
    restore_mode: ALWAYS_OFF
    effects: *led_effects

  - platform: monochromatic
    id: blue_led
    output: output_blue
    default_transition_length: 25ms
    restore_mode: ALWAYS_OFF
    effects: *led_effects

output:
  - platform: ledc
    id: output_red
    pin: GPIOXX

  - platform: ledc
    id: output_green
    pin: GPIOXX

  - platform: ledc
    id: output_blue
    pin: GPIOXX



